### ISSUE TITLE
Suggestion: Save Stats log

### ISSUE THREAD

**Issue by xcloudx01** [FreneticLLC/KeyboardChatterBlocker#41]
Hi, I love the program! I have a suggestion: Could the stats page's contents be auto-saved? So when the system is rebooted, the stats are retained.

I'd love to be able to gather chatter data over a week and several restarts and find to which keys chatter the most.

**Comment by abraxas86** [comment]
It would be great if we could export the data to csv, too!

**Comment by mcmonkey4eva** [comment]
There's now a new option to save persistent stats, under the Other Settings tab.

Will be included in upcoming release 1.18

**Comment by mcmonkey4eva** [comment]
[Release 1.18](https://github.com/FreneticLLC/KeyboardChatterBlocker/releases/tag/1.18) is out now including this new feature!
