### ISSUE TITLE
Chocolatey package update?

### ISSUE THREAD

**Issue by teknowledgist** [FreneticLLC/KeyboardChatterBlocker#43]
The [Chocolatey package for keyboard-chatter-blocker](https://community.chocolatey.org/packages/keyboard-chatter-blocker/) is out-of-date.  

I am interested/willing to (co-) maintain it, but the community repository admins are reluctant to hand over control of an author-maintained package (even if it isn't really maintained any longer).  They need either you to add me as a maintainer or you to agree (here or email) for them to add me.  I have a number of other packages that I maintain, and I think I do them fair justice (as I would for this one too).  

Otherwise, the package just languishes and anyone who wants to use it doesn't get to enjoy the fixes/enhancements.

Thanks.

**Comment by teknowledgist** [comment]
All you need to do is reply here indicating that you are OK with me co-maintaining the `keyboard-chatter-blocker` Chocolatey package, and I will get (and keep) it up-to-date.

If you reply that you do not want to give up full control, then I will stop asking because it is your product -> your decision.

Thanks.

**Comment by mcmonkey4eva** [comment]
I don't actively focus on this project, I'll look into it when I have time. My chocolatey files are on a different machine that i'd need to go searching to dig back up.

**Comment by teknowledgist** [comment]
Hi.  I don't think it is necessary to dig out your Chocolatey files unless you want to restart your maintenance of the Chocolatey package.  If (and that is the big question) you are OK with me maintaining the Chocolatey package, I certainly don't need your Chocolatey files.  😄 

What I am proposing is that you continue whatever work you want on KeyboardChatterBlocker, and I will simply monitor it for new releases and create/submit an updated Chocolatey package shortly thereafter.  IMHO, you get all the "glory" as the author and as a co-maintainer of the package, and you don't need to do any more work.  

I suppose you do need to trust that I will create a good/safe Chocolatey package, but I would hope that [my other Chocolatey packages](https://community.chocolatey.org/profiles/teknowledgist) would provide evidence in support of that.  Probably the best demonstration of my engagement is the discussion for [Anaconda3](https://community.chocolatey.org/packages/anaconda3#discussion).

Again, if you want to maintain total control over the distribution of your package and/or don't trust me, then just let me know and I won't bother you again.

Thanks.

**Comment by mcmonkey4eva** [comment]
Made new scripts, and put the new Chocolatey files in the repo instead of somewhere down yonder to get lost, so should be able to keep up publishing to Chocolatey from here on out.
